version: 2.1

executors:
  node_executor:
    docker:
      - image: circleci/node:12.9.1-browsers

commands:
  restore_yarn_cache:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
  save_yarn_cache:
    steps:
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  setup_job:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_yarn_cache
      - run:
          name: install modules
          command: |-
            cd src
            yarn install
      - save_yarn_cache
  format_job:
    steps:
      - checkout
      - restore_yarn_cache
      - run:
          name: check code format
          command: |-
            cd src
            yarn prettier:ci
            yarn lint

workflows:
  check:
    jobs:
      - setup_job
      - format_job:
          requires:
            - setup_job
